In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Meta
FEATURES = 4
LOWER, UPPER = -500, 500
POP_SIZE = 5
K_BEST = int(.7 * POP_SIZE)

In [3]:
# initialize random population
population = np.random.uniform(low=LOWER, high=UPPER, size=[POP_SIZE - 1, FEATURES])
population = np.vstack((population, np.array([420, 420, 420, 420], dtype=np.float32)))

population_ph = tf.placeholder(tf.float32, [None, FEATURES])

In [16]:
# fitness function; schwefel
fitness = 418.9829 * FEATURES - tf.reduce_sum(
    tf.multiply(population_ph,
             tf.sin(tf.sqrt(tf.abs(population_ph)))),
    reduction_indices=[1])

# descending order
top_vals, top_inds = tf.nn.top_k(fitness, k=POP_SIZE)

# Interested in minimum values; reverse returned population
population_sorted = tf.gather(population_ph, tf.reverse(top_inds, [0]))



In [17]:
with tf.Session() as sess:
    
    feed_dict={population_ph: population}
    ps = sess.run(population_sorted, feed_dict=feed_dict)
    print(ps)
    

[[ 420.          420.          420.          420.        ]
 [ 383.65182495 -171.90982056 -305.16052246  -52.55737686]
 [-402.6557312  -307.60183716  -24.39159393 -297.6149292 ]
 [-359.67532349  168.93582153 -105.19004822  -28.88232994]
 [ 167.29554749  -68.20900726 -456.77352905  -72.24406433]]
